### ISSUE TITLE
FEAT. v.0.3 - User Groups

### ISSUE THREAD

**Issue by Olsyx** [Darkatom/Alpaca#16]
The main idea is that users can join into groups —say, for example, a cultural association— and organize private activities, etc.

Let's break it down:
- Groups can be created by any authenticated user.
  - Groups have logos.
  - Groups have descriptions (everything has a description).
  - Groups may have contact information, but they don't operate as users.
- Group index page. A list of all groups.
- Group management page.
    - Settings allowing automatic joining, requests, etc.
    - The usual throw out, accept join request, etc. per group.
- List of all groups I am part of page, with Leave button for each..
  - Groups may have more than one admin. Admin's can't throw other admins out.
  - Groups may have activities related to them, but only the activity's author may manage it.
- Users' new setting options:
  - Show groups I admin.
  - Show groups I'm part of.
- Activities may relate to groups.
  - Select the group from a select dropdown list of "groups I'm a part of"
  - New settings options: 
    - Allow only people from my group, no one else.
    - Automatic join for my group, request from everyone else.
    - Everyone must request.
    - Free for everyone.
- Activities related to a group are listed on the group's page.
- Index activity search must take into account groups.

**Comment by sirikon** [comment]
Groups may have more than one admin. Admin's can't throw other admins out: I would add here the figure of the Superadmin or the Owner.

Also, admins should be able to remove activities.

**Comment by Olsyx** [comment]
So far:
- Group Model has been created.
- Group views (admin, member and anon) have been fully implemented.
- Groups can be created (tested).
- Groups can be edited (needs testing).
- Users joining, promoting, demoting and kicking has been fully implemented (needs testing).
- Activity relations to the group can be accepted and rejected (needs testing).
- Events and Activities are visible on the group page (needs testing and design).
- Activity and Group views have been separated into their own folders.
- Some CSS changes have taken place, since Activity, Group and User are similar in so many ways.
- `_group.scss` has been created for Group view and management pages.

Missing:
- Pots of testing.
- An index of all groups.
- Activities asking the group to be related to them.
- `+ New Event` button for admins of a group at the group page.
- Fixing Activity Views routing, since the HTMLs are now on a different folder.
- Some other things.

**Comment by Olsyx** [comment]
- [x] An index of all groups.
- [x] Fixed Activity Views routing.
- [ ] New Event button and functionality.
- [x] Relating Activities to the group.
- [x] Testing overall member management.

**Comment by Olsyx** [comment]
Ok, so everything is done.

I finished yesterday night and I was waiting for that last checkbox, but I'm just going to ignore it since I consider it would be more of the Event's thread, being a new feature and all.

All these new things, specially the settings part, will need heavy testing. I keep coming up with bugs and crashes. I shall leave it for now and as soon as everything is set for the 0.3, I will start 0.4 as the Beta Testing Update.
