### ISSUE TITLE
FEAT. v.0.3 - Events

### ISSUE THREAD

**Issue by Olsyx** [Darkatom/Alpaca#17]
Events are groups of activities taking place all at the same place, and almost at the same time. Events' overall behavior is the one of any regular activity's, but:

- Events may only be created in a group, by one of the admins of said group.
- Events have an author (the group), organizers (the admins) and attendants (users).
- All admins are considered organizers.
  - Although we understand events may have volunteers, this is the management page for attendants, not the actual event. There's no reason for volunteers to manage an event page. 
- Events have a list of activities related to them. 
- Therefore, activities should be relatable to an event.
  - Hence, the activity's start and end time cannot surpass those of the event.
  - The "Where" text will still be in use, since an activity can take place in several locations inside a building, or we could be talking about a gincana.
  - New settings options:
    - Allow joining only after having joined the event.
    - Allow joining with request only after having joined the event.
    - Request joining, regardless of having joined the event.
    - Free joining.
- Events will be displayed among other activities at the index page, but will be distinct.
- Events shall be taken into account for searching at the index.

**Comment by Olsyx** [comment]
As a note: with the Issue #16 there arises a problem; events should only be available after a group has been selected, as anyone should be allowed to start an activity related to an event.

My proposal is that admins of the group can manage activities at the events, such as the following flow:
- User creates activity -> selects group they are part of as a member -> select ongoing event -> submit activity -> activity starts working as normal (?)
- Group gets email (activity request for event) -> goes to event page -> manage activity requests -> accept/reject proposed activity.
- User gets email about decision.
- Activity keeps working as normal.

There could be extra settings about this: Allow any users to start an activity for this event? Only group members? Only organizers? Any of those, upon request or freely?

Also, we'll need a new functionality for activities (and sessions, and events, since we're at it):
- Cancel (rather than delete?) activity/session/event + email to everyone attending.

**Comment by sirikon** [comment]
I would add some customization and branding for the events, like icon, images, brand color, etc.

**Comment by Olsyx** [comment]
v.0.4 :D

**Comment by Olsyx** [comment]
Everything, except the relating Activities to Events, Canceling and some options, has been implemented.

It needs, however, HEAVY testing. And it doesn't display correctly at the index, which, by the way, I made it happen in a really shady way.

Due to the increasing complications around implementing new things and keeping the rest stable, I'm dis-labeling this issue and keeping it for the future. The current state is unsustainable and I need to do some heavy refactoring before continuing.

**Comment by Olsyx** [comment]
Everything has been implemented and tested.

- Activities for an event are now created from _inside_ the event. This way, we prevent messy form controls and only people from the event are allowed to create and relate events.
- Users wanting to join one of these activities will have to wait until the activity is accepted in the event (in case it needs confirmation), then join the event, and from there it depends on settings.

Sirikon's proposal for branding it's still taken into consideration, but since this issue was for event implementation, I close these thread and another shall be opened in due time.
