### ISSUE TITLE
FEAT. v.0.3 - Images & Avatars

### ISSUE THREAD

**Issue by Olsyx** [Darkatom/Alpaca#18]
We'll open a space on our server for images.

Concretely:
- User avatars.
  - One per user overwritten each time they upload one.
  - The last avatar will be stored, even if they choose to use Gravatar instead.
- Group avatar, same rule as user avatars.
- Activity / Event covers.

They will be stored on a folder in the server. Sirikon tells me _ImageField_ exists in Django, so that's what we'll use.

**Comment by sirikon** [comment]
We could use thumbor for some thumbnails

**Comment by Olsyx** [comment]
I very much agree with that suggestion. It would be very interesting!

_______________________________________

- [x] Images are uploaded with a unique name per user/activity
- [x] Images with the same name are overwritten
- [x] Users have avatars
- [ ] Users may choose Gravatar instead
- [x] Groups have avatars
- [x] Activities have covers
- [x] Events have covers and more image slots.

**Comment by Olsyx** [comment]
This was covered with the Event and Group updates.

I'm leaving Gravatar for later implementation, since the web needs a whole rework first.
